app:
  name: "Rubri-Backend"
  version: "0.1.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

database:
  type: "postgresql"  # Use PostgreSQL for production
  host: "db"  # Docker service name or production DB host
  port: 5432
  username: "rubri_user"
  password: "strong_password"  # Should be set via environment variable in production
  database: "rubri_prod"
  pool_size: 10
  max_overflow: 20
  # SQLite fallback configuration
  use_sqlite_fallback: true  # Fall back to SQLite if PostgreSQL is not available
  sqlite_path: "/data/rubri_prod.db"

storage:
  base_dir: "/data/received_data"

llm:
  provider: "openai"
  model: "gpt-4"
  temperature: 0.1  # Lower temperature for more consistent results in production

development:
  use_mock_responses: false

# Redis configuration for Celery
redis:
  url: "redis://redis:6379/0"  # Docker service name for Redis

# Email configuration
email:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  from_email: "noreply@rubri.ai"
  from_name: "Rubri Interview Assistant"
  # SMTP credentials should be set via environment variables:
  # SMTP_USERNAME and SMTP_PASSWORD

# Frontend URL for email links
frontend_url: "https://app.rubri.ai"

# Google OAuth configuration
google_oauth:
  client_id: ""  # Set via GOOGLE_CLIENT_ID environment variable
  client_secret: ""  # Set via GOOGLE_CLIENT_SECRET environment variable
  redirect_uri: "https://api.rubri.ai/api/v1/auth/google/callback"

# JWT Configuration
jwt:
  secret_key: ""  # Set via JWT_SECRET_KEY environment variable
  algorithm: "HS256"
  access_token_expire_minutes: 1440  # 24 hours
  refresh_token_expire_days: 30